### PR TITLE
Allow for creating ghr files when not releasing

### PR DESCRIPTION
**Pull request by hazcod**
In my case, I need to know what release would be the next before actually releasing.

### CODE REVIEW

**Comment by christophwitzko** [comment]
The `.ghr` file is created for the use of https://github.com/tcnksm/ghr
If I understand you right you want semantic-release to return the latest release so you can additionally upload files to the release?

**Comment by hazcod** [comment]
Exactly!

**Comment by christophwitzko** [comment]
Okay, and why are you not using the `.version` file?
Sorry for all the questions, I really want to understand your case. 😊

**Comment by hazcod** [comment]
It seems that `.version` does exactly what I need!
I think my main issue is that sometimes I want to force a new deploy without having any semantic commits, so I need the current version in `.version` while semantic-release fails because of 'no changes'.

**Comment by christophwitzko** [comment]
Okay, thank you for the elaboration. What you describe is not really the semantic way of releasing or deploying. If a version has been built once, it should never be altered afterward.
If you still want to do that, I would suggest using a simple bash script to request the [GitHub api](https://developer.github.com/v3/repos/releases/#get-the-latest-release) and get the latest release if semantic-release fails.
Thanks for your understanding.

**Pull request closed without merging**
