### PR TITLE
feat: Add from SHA to GetCommits

### PR DESCRIPTION
**Pull request by cliedeman**

### CODE REVIEW

**Comment by cliedeman** [comment]
Groundwork for https://github.com/go-semantic-release/provider-gitlab/issues/1

**Comment by christophwitzko** [comment]
Hey Ciaran, thanks for this PR. 👌 

At the moment the `GetCommits` function is supposed to the all commits from the provider. The limitation of the commits that are considered for the next release is happening here: https://github.com/go-semantic-release/semantic-release/blob/master/pkg/semrel/semrel.go#L15

As your PR suggests, it would be much smarter to pass the `FromSHA` to the `GetCommits` function, but this will be a breaking change for the plugin interface. I am happy to merge that, but I have a few smaller breaking changes, I will add to this PR. 👌

**Comment by cliedeman** [comment]
Hi Christoph, great thanks. 

If you are making breaking changes do you think we could do an Annotations or Metadata object added to _all_ objects.

E.g.

```
message Annotation {
  string name = 1;
  string data = 2;
}
```

```
message RawCommit {
  string SHA = 1;
  string raw_message = 2;
  map<string, Annotation> annotations = 3;
}
```

The idea being that custom plugins (or standard ones) can add arbitary data that can possibly be consumed later on in the pipeline.

Example Use cases: 
* Flag specific commits, .e.g. commits that affect sql migrations. Add an annotation to the commit that can alter the generated change to add a _may require migrations_ note
* Gitlab specific - Retrieve [merge requests](https://docs.gitlab.com/ee/api/commits.html#list-merge-requests-associated-with-a-commit) linked to a commit


Ciaran

**Comment by christophwitzko** [comment]
Sounds good, we could also add information about the commit author or if the commit was signed. I think that a simple key-value map (`map<string, string>`) should be enough.

**Comment by cliedeman** [comment]
Sounds good. How about

### Get Commit APIs
- https://docs.github.com/en/rest/reference/repos#list-commits
- https://docs.gitlab.com/ee/api/commits.html#list-repository-commits

```proto
message Comitter {
  string name = 1;
  string email = 2;
  google.protobuf.Timestamp date = 3;   
}

message RawCommit {
  string SHA = 1;
  string raw_message = 2;
  Comitter author  = 3;
  Author author = 4;
  # Not sure if this should be standard. Gitlab requires a call for every single commit...
  verified = 5;
  web_url = 6;
  map<string, string> annotations = 7;
}

message Change {
  bool major = 1;
  bool minor = 2;
  bool patch = 3;
}

message Commit {
  string SHA = 1;
  repeated string raw = 2;
  string type = 3;
  string scope = 4;
  string message = 5;
  Change change = 6;
  Comitter author  = 7;
  Author author = 8;
  # Not sure if this should be standard. Gitlab requires a call for every single commit...
  verified = 9;
  web_url = 10;
  map<string, string> annotations = 11;
}

message Release {
  string SHA = 1;
  string version = 2;
  web_url = 3;
  map<string, string> annotations = 3;
}
```

**Comment by christophwitzko** [comment]
I would keep it simple and stick to your first suggestion an only add `map<string, string> annotations`. Committer and Author are useful, but I would keep it out of the struct, and add it to the annotations map, if needed.

**Comment by cliedeman** [comment]
@christophwitzko I have added the annotations. Ist there any other breaking changes you still want to add?

**Comment by christophwitzko** [comment]
Hey @cliedeman, I have been thinking a lot about these changes, but changing the function signature will break all providers and will actually prevent semantic-release to release itself 🤦🤣 (which would be necessary to update the provider plugins).

So my proposal is the following:
- leave the plugin interface as it is and pass a ref range string as sha, like `<from_sha>...<to_sha>`
- update plugins to handle sha parameters with `...` accordingly

Of course, this is not the clean way to do it and will also be a breaking change, but we can handle it much smoother with backward compatibility.
In the future, I would like to use the [`VersionedPlugins`](https://github.com/hashicorp/go-plugin/blob/v1.3.0/server.go#L73) feature to support breaking changes in plugin interfaces.

**Comment by cliedeman** [comment]
Hi @christophwitzko good to hear from you again

If you want zero breaking changes we can do a phased approach and support both arguments for a release or 2

Updated
```proto
message GetCommits {
  message Request {
    string SHA = 1;
    string from_SHA = 2;
    string to_SHA = 3'
  }
  message Response {
    repeated RawCommit raw_commits = 1;
    string error = 2;
  }
}
```

Future
```proto
message GetCommits {
  message Request {
    # string SHA = 1; deprecated
    string from_SHA = 2;
    string to_SHA = 3'
  }
  message Response {
    repeated RawCommit raw_commits = 1;
    string error = 2;
  }
}
```

**Comment by christophwitzko** [comment]
I like your approach!
We can just rename `string SHA = 1;` to `string to_sha = 1;`. that should be enough ☺️

**Review by christophwitzko — APPROVED** [review]

**Pull request merged**
