### PR TITLE
Fix: Added gitlab docker image

### PR DESCRIPTION
**Pull request by cliedeman**

### CODE REVIEW

**Comment by christophwitzko** [comment]
Hey @cliedeman, thanks for this PR but I think it is not necessary to have semantic-release as a docker image. It's faster and simpler to just download the executable from the GitHub release page. Or do you have a scenario in mind where having semantic-release as a docker image can be useful?

**Comment by cliedeman** [comment]
It's more of a why not? Its so easy with gitlab and it's registry.

I do prefer using an image instead of downloading a binary.

Example gitlab job:
```
release:
  image: go-semantic-image
  stage: release
  when: manual
  only:
    - master
  script:
    - release
```

I also have some ideas around plugins which could be useful

Example dockerfile

```
FROM go-semantic-release:1.0.0
ADD myplugin plugins/
```

**Comment by christophwitzko** [comment]
Okay, this is nice. I didn't know that. 👍

**Comment by christophwitzko** [comment]
I prefer to use GitHub Actions to build the docker image, so everything is in the same place. I created a new PR #52

**Pull request closed without merging**
